querier/prometheus_wrapper.go
storage/elasticsearch/integration_test.go
storage/elasticsearch/resolver.go
storage/resolver.go

resolves https://github.com/digitalocean/vulcan/issues/37
This allows the grafana and the `/graph` page to query what metrics exist in vulcan to help the user write queries.

querier: implements metadata API

---

.travis.yml

It looks like `curl https://glide.sh/get | sh` fails to install in travis (https://travis-ci.org/digitalocean/vulcan/builds/154797608)
Instead of curl executing this script from the Internet that fails in the travis ci container, this change makes it so we download a known version of glide, verify the checksum, and place the binary in $GOPATH/bin (which is already part of the path).

travis: installs glide v0.11.1 from tarball

---

cmd/indexer.go
convert/promtexttosg.go
convert/promtexttosg_test.go
indexer/indexer.go
ingester/ingester.go
kafka/ack_source.go
querier/series.go
querier/wrapper.go

- Convert to convert prometheus.storage.remote.WriteRequest to vulcan.bus.Sample
- Changes made convert package and kafka 
- Added debug logging wrapper, ingester, indexer

convert: migrate to remote.WriteRequest from dto.MetricFamily

---

forwarder/writer.go

Logging each batch write at info level is too verbose.

forwarder: log each batch write at debug level not info

---

.travis.yml
dev/vulcan.dockerfile

This upgrades the version of glide used in Travis and in the docker-compose docker environment to the current latest (v0.12.2). When modifying dependencies, glide v0.12.x will sort the yaml and lock file to make future diffs more pleasant.

tools: set glide to v0.12.2

---

glide.lock
glide.yaml

* removes unnecessary dependencies
* sets semver in yaml on dependencies where available
* updates glide.lock
When we were implementing the scraper more directly (before Prometheus' generic write API), we needed to specify all the dependencies to fulfill service discovery. Now, we don't directly need those dependencies, so we can have a simpler glide yaml.
Also, sets semver (thanks to glide config-wizard) where available on our yaml dependencies.

cleans up glide yaml

---

.travis.yml

Glide caches the repos it uses when fulfilling dependencies at `~/.glide/cache`
Having travis know about this cache should speed up CI.

persist glide cache on travis

---

bus/ack_source.go
bus/datapoint.go
bus/metric.go
bus/sample.go
bus/sample_group.go
bus/source.go
cassandra/sample_writer.go
cassandra/writer.go
cmd/forwarder.go
cmd/ingester.go
glide.lock
glide.yaml
ingester/ingester.go
ingester/writer.go
kafka/ack_source.go
kafka/source.go
main.go
model/doc.go
model/timeseries.go

The ingester worker should be able to load balance Kafka messages between all active ingesters. This is done with Kafka Consumer Groups.
I wanted to bring our data structs more in-line with what we're now utilizing with the Prometheus generic remote storage API. The remote storage structs are simpler than the exposition format protobuf structs we were modeling in the `bus` package, though these structs still exist (for now). I commented the structs in the `bus` package as deprecated. The Indexer still relies on them (for now). 
I chose to avoid the `bus` package and make a new `model` package since these structs for `TimeSeries`, `Sample`, and `TimeSeriesBatch` are used in components that don't actually interact with the message bus.
The refactored ingester uses a new `kafka.Source` and a …

ingesters should load balance messages

---

querier/wrapper.go

The querier is logging too much information at info level. Most of these are really debug-type messages that a function was being called and with what args. 
Also, logs the length of iterators instead of logging the whole list of iterators which can be quite large.

makes querier less verbose

---

.travis.yml
Dockerfile
Makefile

This adds `make push` and `make docker` to the Makefile. This allows easier creation of runnable Vulcan containers available on docker hub (for those who have hub access to publish). For now, this pushes to the docker hub repo `dovulcan/vulcan`.
The goal is to make it easier to run Vulcan through docker while developing. `make docker` is still available to those without rights to publish to docker hub.
I was experimenting with having travis auto-build the docker container and push it, but was having issues with the containers being produced.

make publishing docker tags easier

---

cassandra/writer.go
cmd/ingester.go

In order to gain better insight into the ingester, we need to see how Cassandra writes are performing. This adds two histograms for write durations: one for a single sample, and the other for writing the entire batch. As a side-effect from histograms, we also get a count of batch writes and sample writes.
Also added a gauge of Cassandra workers to show how many goroutines are active and idle.

adds write duration telemetry to cassandra

---

cmd/indexer.go
convert/promtexttosg.go
indexer/indexer.go

- fixes connection error to ES
- this fix is meant to be temporary.  The real fix from revisiting how we're using indexer worker goroutines.

indexer: custom http client for ES client

---

bus/writer.go
bus/writer_mock.go
cassandra/writer.go
cmd/flags.go
cmd/forwarder.go
forwarder/writer.go
forwarder/writer_test.go
kafka/source.go
kafka/writer.go

- Refactor kafka package to use an asynchronous Fafka client instead of the prior synchronous one to speed up the incoming data flow from prometheus to itself.
- Add prometheus gauge in Forwarder write to track the number of Timeseries objects sent per write request (removed logging in this area).  
- Implement the Kafka writer as a prometheus collector to track write successes and failures, and current enqueued messages.
- Handling of SIGINT and SIGTERM signals for gracefully shutdown of the Kafka Writer.
- Minor logging changes throughout the app.

kafka: switch to async consumer & implement prom exporter

---

cassandra/writer.go
cmd/forwarder.go
cmd/ingester.go

When samples are written to the Cassandra uncompressed table, they are now written with a configurable TTL (seven days by default). The goal is to have cheap/automatic cleanup of old data. The TTL on the uncompressed table should be enough of a window to have the (not-yet-implemented) compactors store 2-hour blocks of samples from the uncompressed table into the compressed table as a blob. 
Having a TTL right now before implementing the compactor allows us to cap the amount of disk we need for our cluster with a given ingest rate and ttl. The TTL can be set to `0s` for no TTL.

ingester sets cassandra ttl on uncompressed samples

---

cmd/querier.go

Like #67, setting the driver to be token-aware allows Vulcan to operate quicker since queries are directed to a Cassandra node that owns the data for the given query.

querier: read with token-aware driver

---

.gitignore
.travis.yml
Dockerfile
Makefile
cmd/version.go
main.go
scripts/licensecheck

* sets build flags `gitSummary` and `goVersion`
* `vulcan vendor` displays git summary and go version set in makefile
* simplifies tar creation
* uses `.makefile/{vendor,docker}` touchfiles to do less work
* fixes licensecheck so it doesn't check vendor files
* fixes make lint so it doesn't check vendor files
* uses git summary everywhere instead of git short hash and git version
* git summary includes "-dirty" if running makefile with uncommitted changes

makefile: simpler; faster; fixes for lint and licensecheck

---

kafka/writer.go

- switch to Snappy compression from GZIP to alleviate some of the CPU overhead put on the ingester required for decompression.

kafka: snappy compression for producer messages

---

cmd/forwarder.go

- Re-adds Prometheus registration to forwarder, which was accidentally removed earlier.

forwarder: register forwarder to prometheus

---

cassandra/iterator.go
forwarder/handler.go
forwarder/writer.go
forwarder/writer_test.go
glide.lock
glide.yaml
querier/querier.go
querier/wrapper.go

Updates to prometheus v1.2.1 and updates our code to match the new query interfaces and new location of the ZeroSamplePair.
This is necessary for the upcoming compactor work since the compactor needs the varbit encoding publicly exposed which happened in prometheus 1.2.0.

updates prometheus to v1.2.1 for exposed chunks

---

cacher/accumulator.go
cacher/accumulator_test.go
cacher/cacher.go
cacher/http.go
cacher/iterator.go
cacher/iterator_factory.go
cacher/iterator_test.go
cmd/cacher.go
cmd/flags.go
glide.lock
glide.yaml
kafka/hash.go
kafka/hash_test.go
kafka/key.go
kafka/key_test.go
main.go
model/userdata.go

The cacher combined with the compressor is meant to replace the "ingester" part of Vulcan. The cacher keeps a configurable window of most recent samples from Kafka in-memory. The querier serves all the samples it can from compressed/persisted chunks stored in Cassandra, and then gets the most recent metric samples from the cacher.
The cacher stores metrics in-memory in varbit-encoded chunks for memory efficiency and also returns results to the querier in varbit-encoded responses to minimize network transfer.
This PR is a first pass at a cacher that can share load among other cachers via a Kafka consumer group and advertise how to connect to the cacher via Kafka metadata.
Following PRs will be for the compressor, and a querier that knows how to utilize both the cacher and compressor data. …

cacher: in-memory metrics

---

.travis.yml
Makefile

Updates travis install of glide to v0.12.3.
Updates makefile command to install dependencies to use the "-v" flag which tells glide to remove our depedencies' vendor directories instead of manually running a "rm -fr ..." command in the makefile.

glide: update v0.12.3; remove vendor's vendor automatically
